[package]
name = "roulette-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.0-pre.0"
tui = "0.15"
termion = "1.5"
